apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-helm-chart
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginx
  source:
    repoURL: 'https://github.com/HIRO-MicroDataCenters-BV/argocd-demo02.git'
    path: 'hello-world-chart/hello-world'
    targetRevision: 'HEAD'  # Use the latest commit
    helm:
      valueFiles:
        - values.yaml
      releaseName: my-release
      chart: hello-world
      version: '*'  # Using wildcard to track the latest version
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
